### PR TITLE
OGM-946 Test all the Entity listeners and Callback methods annotation

### PR DESCRIPTION
**Pull request by Ilonich**
Added tests

### CODE REVIEW

**Comment by schernolyas** [comment]
It is fix for https://hibernate.atlassian.net/browse/OGM-946

**Comment by schernolyas** [comment]
Hi @Ilonich !

Could you please use @After and @Before annotations for decrease code duplication.  You can see other inheritors for get example

**Review by schernolyas — CHANGES_REQUESTED** [review]
Hi @Ilonich !

Could you please use "@After" and "@Before" annotations for decrease code duplication. You can see other inheritors for get example

**Comment by Ilonich** [comment]
@schernolyas Thanks, code changed.

**Pull request merged**
